import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0A0F1F',
        alignItems: 'center',
        justifyContent: 'center',
    },
    backgroundGradient: {
        backgroundColor: '#0A0F1F',
    },
    backgroundGradient: {
        backgroundColor: '#0A0F1F',
    },
    // ============ TITLES & TEXT ============
    title: {
        fontSize: 48,
        fontWeight: 'bold',
        color: '#00F5FF',
        marginBottom: 10,
        textShadowColor: '#00F5FF',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 20,
        letterSpacing: 3,
    },
    subtitle: {
        fontSize: 18,
        color: '#00F5FF',
        marginBottom: 30,
        opacity: 0.8,
        letterSpacing: 2,
    },
    questionNumber: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#FF2D95',
        marginBottom: 15,
        letterSpacing: 2,
        textTransform: 'uppercase',
    },
    questionText: {
        fontSize: 24,
        color: '#E0E0E0',
        textAlign: 'center',
        marginBottom: 40,
        fontWeight: '600',
        lineHeight: 32,
    },
    scoreText: {
        fontSize: 72,
        fontWeight: 'bold',
        color: '#00F5FF',
        marginBottom: 10,
        textShadowColor: '#00F5FF',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 20,
    },
    scoreLabel: {
        fontSize: 18,
        color: '#8A2BE2',
        marginBottom: 30,
        letterSpacing: 2,
    },
    // ============ BUTTONS ============
    button: {
        width: '80%',
        height: 56,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#00F5FF',
        marginBottom: 15,
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 15,
        elevation: 10,
    },
    buttonText: {
        fontSize: 16,
        color: '#00F5FF',
        fontWeight: 'bold',
        letterSpacing: 2,
    },
    nextButton: {
        width: '85%',
        height: 56,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#00F5FF',
        marginBottom: 15,
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 15,
        elevation: 10,
    },
    nextButtonDisabled: {
        borderColor: '#555',
        opacity: 0.4,
    },
    nextButtonText: {
        fontSize: 16,
        color: '#00F5FF',
        fontWeight: 'bold',
        letterSpacing: 1.5,
    },
    backButton: {
        width: '85%',
        height: 56,
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: '#8A2BE2',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        marginBottom: 10,
        marginTop: 10,
    },
    backButtonText: {
        fontSize: 16,
        color: '#8A2BE2',
        fontWeight: 'bold',
        letterSpacing: 1.5,
    },
    // ============ OPTIONS ============
    optionsContainer: {
        width: '90%',
        marginBottom: 30,
    },
    optionButton: {
        width: '100%',
        paddingVertical: 16,
        paddingHorizontal: 20,
        backgroundColor: 'rgba(0, 245, 255, 0.05)',
        borderRadius: 8,
        marginBottom: 14,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#00F5FF',
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    optionButtonSelected: {
        backgroundColor: 'rgba(0, 245, 255, 0.15)',
        borderColor: '#00F5FF',
        shadowOpacity: 0.8,
        shadowRadius: 15,
        elevation: 10,
    },
    optionButtonCorrect: {
        backgroundColor: 'rgba(0, 255, 156, 0.1)',
        borderColor: '#00FF9C',
        shadowColor: '#00FF9C',
        shadowOpacity: 0.8,
    },
    optionButtonWrong: {
        backgroundColor: 'rgba(255, 59, 59, 0.1)',
        borderColor: '#FF3B3B',
        shadowColor: '#FF3B3B',
        shadowOpacity: 0.8,
    },
    optionText: {
        color: '#E0E0E0',
        fontSize: 16,
        flex: 1,
        fontWeight: '500',
    },
    optionTextSelected: {
        color: '#00F5FF',
        fontWeight: '600',
    },
    // ============ CHECKBOX ============
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 4,
        borderWidth: 2,
        borderColor: '#00F5FF',
        marginRight: 15,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    checkboxSelected: {
        backgroundColor: '#00F5FF',
        borderColor: '#00F5FF',
    },
    checkmark: {
        color: '#0A0F1F',
        fontWeight: 'bold',
        fontSize: 14,
    },
    // ============ PROGRESS ============
    progressBar: {
        width: '85%',
        height: 6,
        backgroundColor: 'rgba(0, 245, 255, 0.1)',
        borderRadius: 3,
        marginBottom: 25,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#00F5FF',
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 5,
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#00F5FF',
        borderRadius: 3,
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 10,
        elevation: 5,
    },
    // ============ QUESTION CONTAINER ============
    questionContainer: {
        width: '90%',
        paddingHorizontal: 20,
        paddingVertical: 25,
        alignItems: 'center',
        marginBottom: 20,
        backgroundColor: 'rgba(0, 245, 255, 0.03)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(0, 245, 255, 0.2)',
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 5,
    },
    // ============ INPUT ============
    inputName: {
        width: '100%',
        height: 56,
        backgroundColor: 'rgba(0, 245, 255, 0.05)',
        borderRadius: 8,
        paddingHorizontal: 16,
        fontSize: 16,
        marginBottom: 20,
        color: '#00F5FF',
        borderWidth: 2,
        borderColor: '#00F5FF',
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    // ============ RESULTS ============
    resultsContainer: {
        width: '90%',
        alignItems: 'center',
        paddingVertical: 20,
    },
    resultCard: {
        width: '100%',
        padding: 25,
        backgroundColor: 'rgba(0, 245, 255, 0.03)',
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#00F5FF',
        marginBottom: 20,
        alignItems: 'center',
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 15,
        elevation: 10,
    },
    resultStats: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-around',
        marginBottom: 25,
    },
    statBox: {
        alignItems: 'center',
        paddingHorizontal: 15,
    },
    statNumber: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#00F5FF',
        marginBottom: 5,
    },
    statLabel: {
        fontSize: 12,
        color: '#8A2BE2',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    finishButton: {
        width: '100%',
        height: 56,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#00FF9C',
        marginBottom: 15,
        shadowColor: '#00FF9C',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 15,
        elevation: 10,
    },
    finishButtonText: {
        fontSize: 16,
        color: '#00FF9C',
        fontWeight: 'bold',
        letterSpacing: 1.5,
    },
    // ============ RANKING ============
    rankingContainer: {
        width: '100%',
        marginTop: 25,
        paddingHorizontal: 15,
    },
    rankingTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FF2D95',
        marginBottom: 20,
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
    },
    rankingItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 18,
        backgroundColor: 'rgba(0, 245, 255, 0.05)',
        borderRadius: 8,
        marginBottom: 10,
        borderLeftWidth: 4,
        borderLeftColor: '#00F5FF',
        borderWidth: 1,
        borderColor: 'rgba(0, 245, 255, 0.2)',
        shadowColor: '#00F5FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    rankingItemTop1: {
        borderLeftColor: '#FFD700',
        backgroundColor: 'rgba(255, 215, 0, 0.08)',
        borderColor: 'rgba(255, 215, 0, 0.3)',
    },
    rankingItemTop2: {
        borderLeftColor: '#C0C0C0',
        backgroundColor: 'rgba(192, 192, 192, 0.08)',
        borderColor: 'rgba(192, 192, 192, 0.3)',
    },
    rankingItemTop3: {
        borderLeftColor: '#CD7F32',
        backgroundColor: 'rgba(205, 127, 50, 0.08)',
        borderColor: 'rgba(205, 127, 50, 0.3)',
    },
    rankingPosition: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#00F5FF',
        minWidth: 40,
    },
    rankingPositionTop1: {
        color: '#FFD700',
    },
    rankingPositionTop2: {
        color: '#C0C0C0',
    },
    rankingPositionTop3: {
        color: '#CD7F32',
    },
    rankingName: {
        color: '#E0E0E0',
        fontSize: 16,
        flex: 1,
        marginLeft: 15,
        fontWeight: '500',
    },
    rankingScore: {
        fontWeight: 'bold',
        fontSize: 18,
        color: '#00F5FF',
    },
    rankingScoreTop1: {
        color: '#FFD700',
    },
    rankingScoreTop2: {
        color: '#C0C0C0',
    },
    rankingScoreTop3: {
        color: '#CD7F32',
    },
    // ============ HUD ============
    hudContainer: {
        width: '90%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 25,
        paddingHorizontal: 15,
        paddingVertical: 12,
        backgroundColor: 'rgba(0, 245, 255, 0.03)',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(0, 245, 255, 0.2)',
    },
    hudItem: {
        alignItems: 'center',
    },
    hudLabel: {
        fontSize: 12,
        color: '#8A2BE2',
        letterSpacing: 1.5,
        marginBottom: 4,
    },
    hudValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#00F5FF',
    },
})

export default styles

